-- HNSW 인덱스를 도로 걷어낸다.
--
-- 앞 마이그레이션에서 깔았지만 Prisma 스키마 언어로는 HNSW를 표현할 수 없다
-- (@@index의 type은 Hash/Gist/Gin/SpGist/Brin까지만 지원). 그래서 DB에만 존재하는
-- 인덱스가 되고, `prisma migrate dev`가 매번 "이거 지울까요?"를 물어보는 상시 드리프트가 된다.
-- 언젠가 실수로 승낙하면 조용히 사라질 물건이다.
--
-- 지금 코퍼스는 글 수십 개 = 청크 수백 개라 코사인 거리 전수 탐색이 1ms도 걸리지 않는다.
-- 청크가 십만 단위로 늘어 실제로 느려지면, 그때 이 인덱스를 raw SQL 마이그레이션으로
-- 다시 깔고 드리프트를 감수하면 된다.
DROP INDEX "DocChunk_embedding_hnsw_idx";
